### ISSUE TITLE
Issue with submitting a Json stringified parameter when using a .proto for state generation.

### ISSUE THREAD

**Issue by Nova38** [hyperledger-labs/cckit#28]
Thanks for the fantastic work on this tool. 

I found the use of `.proto` to be a good fit for a project I am working on, manly as I needed to make sure that the types are the same though both the chaincode, a nodejs server, and a frontend. In particular i found that there were some good buf/protoc extentions that would generate typescript classes that could canonically sterilize the assets to Json.  I have a ruff design of my own `.proto`, but before i started to work on expanding it i decided to test out if using a `.proto` would let me send a json version of the document so I was trying out the (cpaper_extended)[https://github.com/hyperledger-labs/cckit/tree/main/examples/cpaper_extended] example.  I first tried it completely unchanged and got the bellow error about the parameter being unable to parse as it was an invalid wire-format. I figured that the issue might be that the router was setup with the defparam which only accepts Proto or String parameters it looks like. So, I switched the router to use the param.Struct instead, like in the cars example, however i ended up getting the same error response. Is there a way to be able to use the proto files to model the state and the methods and be able to send the chaincode stringified json? 

```go
r.
		// read methods
		Query("list", queryCPapers).

		// Get method has 2 params - commercial paper primary key components
		Query("get", queryCPaper, param.Struct("id", &schema.CommercialPaperId{})).
		Query("getByExternalId", queryCPaperGetByExternalId, param.String("externalId")).

		// txn methods
		Invoke("issue", invokeCPaperIssue, param.Struct("paper", &schema.IssueCommercialPaper{})).
		Invoke("buy", invokeCPaperBuy, param.Struct("paper", &schema.BuyCommercialPaper{})).
		Invoke("redeem", invokeCPaperRedeem, param.Struct("paper", &schema.RedeemCommercialPaper{})).
		Invoke("delete", invokeCPaperDelete, param.Struct("id", &schema.CommercialPaperId{}))
```

In order to test it out and try to debug the issue I was using the Hyperledger fabric debugger vscode plugin i get the following:

Arguments:
```json
[{
        "invoke": "issue",
        "args": [
            "{\"issuer\": \"test\",\"paper_number\": \"0\",  \"issue_date\": \"2017-01-15T01:30:15.01Z\",\"maturity_date\": \"2017-01-15T01:30:15.01Z\", \"face_value\": 100, \"external_id\": \"test\"}"
        ]
}]
```

Error from the chaincode:
```go
"level":"error","ts":1677739936.167278,"logger":"commercial_paper","caller":"router/response.go:27","msg":"router handler error","path":"issue","message":"unmarshal to proto=*schema.IssueCommercialPaper: proto: cannot parse invalid wire-format data"
```

**Comment by vitiko** [comment]
Hi, Thomas,

> So, I switched the router to use the param.Struct instead

in [current default serializer](https://github.com/hyperledger-labs/cckit/blob/main/serialize/serializer.go#L76) implementation if struct supports proto.Message interface - it wil try to marshal / unmarshal using proto libraries. Thus you receive this error.

**Comment by Nova38** [comment]
ah okay that makes sense. Looking at the link if i set `serialize.PreferJSONSerializer` in the router it should accept the json input?

https://github.com/hyperledger-labs/cckit/blob/6b596ecc26372bf9a10d5c449fc75446ac5a82f2/router/router_test.go#L21

**Comment by Nova38** [comment]
Yep i just confirmed that switching that fixed the issue. Thank you!!
